# Generated by Django 5.0.1 on 2024-02-05 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('birthDate', models.DateTimeField()),
                ('user_type', models.CharField(max_length=255)),
                ('dtti_created', models.DateTimeField(auto_now_add=True)),
                ('dtti_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='student_progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progressPercentage', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.users')),
            ],
        ),
    ]
