# Generated by Django 5.0.1 on 2024-02-05 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_users_activities_users_assessments_users_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tr_user_login_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('dtti_expiry', models.DateTimeField()),
                ('dtti_logout', models.DateTimeField()),
                ('dtti_created', models.DateTimeField(auto_now_add=True)),
                ('dtti_updated', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.users')),
            ],
        ),
    ]
