# Generated by Django 5.0.1 on 2024-02-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_tr_user_login_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tr_user_login_token',
            name='dtti_logout',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tr_user_login_token',
            name='dtti_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
