# Generated by Django 5.0.1 on 2024-02-06 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_tr_user_login_token_dtti_logout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
    ]
