# Generated by Django 5.0.1 on 2024-02-07 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_assessment_questions_assessment_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='assesment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.assessment'),
        ),
    ]
